import os
from dotenv import load_dotenv

load_dotenv()

CAPITAL_API_KEY = os.environ["CAPITAL_API_KEY"]
CAPITAL_EMAIL = os.environ["CAPITAL_EMAIL"]
CAPITAL_PASSWORD = os.environ["CAPITAL_PASSWORD"]
DISCORD_WEBHOOK_URL = os.environ["DISCORD_WEBHOOK_URL"]
IS_DEMO = os.environ["IS_DEMO"].lower() == "true"

CAPITAL_BASE_URL = os.environ["CAPITAL_BASE_DEMO_URL"] if IS_DEMO else os.environ["CAPITAL_BASE_URL"]

EPICS = ["GOLD", "SILVER", "COPPER"]
RESOLUTION = "MINUTE_15"
CANDLE_COUNT = 100

EMA_FAST = 9
EMA_SLOW = 21
RSI_PERIOD = 14
ATR_PERIOD = 14

RSI_LONG_MIN = 40
RSI_LONG_MAX = 70
RSI_SHORT_MIN = 30
RSI_SHORT_MAX = 60

RISK_PER_TRADE = 0.01
SL_ATR_MULT = 1.5
TP_ATR_MULT = 3.0

DB_PATH = "trades.db"

DAILY_SUMMARY_HOUR_UTC = 21
